# Generated by Django 3.2.11 on 2022-01-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.SmallIntegerField(default=0),
        ),
    ]
