# Generated by Django 3.2.11 on 2022-01-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.TextField(default='-1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.TextField(default=',-1'),
        ),
    ]
