# Generated by Django 3.2.11 on 2022-02-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('needs', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('link', models.CharField(default='https://www.soka.ac.jp/inquiries/list', max_length=200)),
                ('tag', models.CharField(default='交通事故報告', max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='https://www.soka.ac.jp/inquiries/list', max_length=200),
        ),
    ]
