# Generated by Django 3.2.11 on 2022-02-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220201_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servey',
            old_name='tag',
            new_name='institution',
        ),
    ]
