# Generated by Django 3.2.11 on 2022-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_tag_servey_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servey',
            name='needs',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='② あなたのニーズに合った学内機関が表示されたと思いますか？'),
        ),
        migrations.AlterField(
            model_name='servey',
            name='question',
            field=models.TextField(verbose_name='③ ②の理由、またはサイトデザインや質問内容等に関する要望があれば教えてください。'),
        ),
        migrations.AlterField(
            model_name='servey',
            name='student_number',
            field=models.IntegerField(verbose_name='① 学籍番号'),
        ),
    ]
