# Generated by Django 3.2.11 on 2022-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220202_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.TextField(default='準備中です', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='voice_first',
            field=models.TextField(default='準備中です'),
        ),
        migrations.AddField(
            model_name='post',
            name='voice_second',
            field=models.TextField(default='準備中です'),
        ),
        migrations.AddField(
            model_name='post',
            name='voice_third',
            field=models.TextField(default='準備中です'),
        ),
    ]
