# Generated by Django 3.2.11 on 2022-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220209_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='map',
            field=models.ImageField(blank=True, upload_to='img/upload'),
        ),
        migrations.AddField(
            model_name='post',
            name='screenshot',
            field=models.BooleanField(default=False, verbose_name='スクリーンショットを表示するか'),
        ),
    ]
