# Generated by Django 3.2.11 on 2022-02-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220209_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='map',
            new_name='maps',
        ),
    ]
