# Generated by Django 3.2.11 on 2022-02-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_map_post_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='場所の選択肢名')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='maps',
        ),
        migrations.AddField(
            model_name='post',
            name='maps',
            field=models.ManyToManyField(to='blog.Maps', verbose_name='場所'),
        ),
    ]
