# Generated by Django 3.2.11 on 2022-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220210_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='maps',
        ),
        migrations.AddField(
            model_name='post',
            name='maps',
            field=models.TextField(default='学生課'),
        ),
        migrations.DeleteModel(
            name='Maps',
        ),
    ]
