# Generated by Django 3.2.11 on 2022-04-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220210_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='選択肢名')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeChoices_re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='選択肢名')),
            ],
        ),
        migrations.CreateModel(
            name='TwoChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='選択肢名')),
            ],
        ),
        migrations.CreateModel(
            name='YesOrNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='選択肢名')),
            ],
        ),
        migrations.RemoveField(
            model_name='servey',
            name='link',
        ),
        migrations.RemoveField(
            model_name='servey',
            name='needs',
        ),
        migrations.CreateModel(
            name='Servey_re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_reasons', models.TextField(default='特になし', verbose_name='上記の具体的な理由をお書きください')),
                ('question_requests', models.TextField(verbose_name='WEB各機能に対する感想・ご意見・ご要望（学生体験談、申し込み方法の提示、説明の口調やサイトデザイン・レイアウト等について）')),
                ('institution', models.CharField(default='交通事故報告', max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('question_already', models.ManyToManyField(to='blog.YesOrNo', verbose_name='あなたに提示された学内機関の申し込み方法をもともと知っていましたか？')),
                ('question_changes', models.ManyToManyField(to='blog.ThreeChoices_re', verbose_name='今までと比べて、学内機関の利用のしやすさに変化はありましたか？')),
                ('question_suitable', models.ManyToManyField(to='blog.ThreeChoices', verbose_name='あなたの「困った」を解決するために適切な学内機関が提示されたと思いますか？')),
                ('question_understanding', models.ManyToManyField(to='blog.TwoChoices', verbose_name='本WEBサイトを利用することによって、申し込み方法を理解することはできましたか？')),
            ],
        ),
    ]
