# Generated by Django 3.2.11 on 2022-04-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220426_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servey_re',
            name='question_reasons',
            field=models.TextField(default=' ', verbose_name='上記の具体的な理由をお書きください'),
        ),
    ]
